export type ProductCatalogEntry = {
  id: string;
  category: string;
  categoryOrder: number;
  subCategory: string;
  name: string;
  imageUrl?: string;
  price?: number;
  priceSmall?: number;
  priceLarge?: number;
  isActive?: boolean;
  sortOrder: number;
};
export const INITIAL_PRODUCT_CATALOG: ProductCatalogEntry[] = [
  {
    id: 's1',
    category: '????',
    categoryOrder: 1,
    subCategory: '????',
    name: '????',
    priceSmall: 400,
    priceLarge: 700,
    sortOrder: 1,
  },
  {
    id: 's2',
    category: '????',
    categoryOrder: 1,
    subCategory: '????',
    name: '????',
    priceSmall: 450,
    priceLarge: 800,
    sortOrder: 2,
  },
  {
    id: 's3',
    category: '????',
    categoryOrder: 1,
    subCategory: '????',
    name: '????',
    priceSmall: 450,
    priceLarge: 800,
    sortOrder: 3,
  },
  {
    id: 's4',
    category: '????',
    categoryOrder: 2,
    subCategory: '??',
    name: '???',
    priceSmall: 350,
    priceLarge: 600,
    sortOrder: 4,
  },
  {
    id: 's5',
    category: '????',
    categoryOrder: 2,
    subCategory: '??',
    name: '???',
    priceSmall: 350,
    priceLarge: 600,
    sortOrder: 5,
  },
  {
    id: 's6',
    category: '????',
    categoryOrder: 2,
    subCategory: '????',
    name: '?????',
    priceSmall: 300,
    priceLarge: 500,
    sortOrder: 6,
  },
  {
    id: 's7',
    category: '????',
    categoryOrder: 2,
    subCategory: '????',
    name: '?????',
    priceSmall: 250,
    priceLarge: 450,
    sortOrder: 7,
  },
  {
    id: 's8',
    category: '????',
    categoryOrder: 3,
    subCategory: '???',
    name: '????',
    priceSmall: 120,
    priceLarge: 200,
    sortOrder: 8,
  },
  {
    id: 's9',
    category: '????',
    categoryOrder: 3,
    subCategory: '???',
    name: '????',
    priceSmall: 150,
    priceLarge: 250,
    sortOrder: 9,
  },
  {
    id: 's10',
    category: '????',
    categoryOrder: 3,
    subCategory: '???',
    name: '????',
    priceSmall: 150,
    priceLarge: 250,
    sortOrder: 10,
  },
  {
    id: 's11',
    category: '????',
    categoryOrder: 4,
    subCategory: '??',
    name: '????',
    priceSmall: 150,
    priceLarge: 250,
    sortOrder: 11,
  },
  {
    id: 's12',
    category: '????',
    categoryOrder: 4,
    subCategory: '??',
    name: '????',
    priceSmall: 150,
    priceLarge: 250,
    sortOrder: 12,
  },
  {
    id: 's13',
    category: '????',
    categoryOrder: 4,
    subCategory: '??',
    name: '????',
    priceSmall: 150,
    priceLarge: 250,
    sortOrder: 13,
  },
  {
    id: 's14',
    category: '????',
    categoryOrder: 5,
    subCategory: '??',
    name: '???',
    price: 30,
    sortOrder: 14,
  },
  {
    id: 's15',
    category: '????',
    categoryOrder: 5,
    subCategory: '??',
    name: '???',
    price: 30,
    sortOrder: 15,
  },
  {
    id: 's16',
    category: '????',
    categoryOrder: 5,
    subCategory: '??',
    name: '???',
    price: 50,
    sortOrder: 16,
  },
  {
    id: 's17',
    category: '????',
    categoryOrder: 5,
    subCategory: '??',
    name: '??',
    price: 15,
    sortOrder: 17,
  },
  {
    id: 's18',
    category: '????',
    categoryOrder: 5,
    subCategory: '??',
    name: '???',
    price: 50,
    sortOrder: 18,
  },
];